Add dos direct memory debugger
caiiiycuk/js-dos.com pull request #125
Opened 2021-02-19 16:33 UTC by matthewturk

This adds a memory debugger routine for the Dos Direct implementation.  This adds a new function `dumpMemory` to the wasm module that creates an instance on the Module called `memoryContents` that includes a dump of the registers, the segment addresses, and (optionally) a copy of the entire memory currently managed by dosbox.

One thing that I didn't do is make the other forms of the registers (`AH`, `AL`, etc), which I figured could be left up to the user.  Perhaps I should put that in?

I'd be really interested in seeing this make its way in, and am totally up for making whatever changes need to be made to get it in!  Thanks very much for walking me through how to approach this on discord, @caiiiycuk !

2021-02-21 17:11 UTC, caiiiycuk requested changes
Can you squash your commits in to one?

2021-02-21 17:11 UTC, caiiiycuk commented on src/dos/direct/cpp/direct-debugger.cpp
> +    emsc_dump_memory_contents(memBase, cpu_regs.ip.dword[0],
wrong indentation

2021-02-21 17:11 UTC, caiiiycuk commented on src/dos/direct/cpp/direct-debugger.cpp
> +	for(Bitu i=0;i<DOS_DRIVES;i++) {
wrong indentation

2021-02-21 17:28 UTC, matthewturk commented
Sorry for the noise with the force pushes, but I think this addresses the changes and properly `ifdef`'s the right things.

2021-02-22 00:49 UTC, caiiiycuk approved these changes

2021-02-22 00:49 UTC, merged